<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\ResourceTemplateRepresentation $resourceTemplate
 * @var \AdvancedResourceTemplate\Form\ResourceTemplateForm $form
 * @var \AdvancedResourceTemplate\Form\ResourceTemplatePropertyFieldset $propertyFieldset
 */

// Copy of original file + replace propertyRow by propertyFieldset.

$translate = $this->plugin('translate');
?>
<?php $this->htmlElement('body')->appendAttribute('class', 'edit resource-templates'); ?>

<?php echo $this->pageTitle($resourceTemplate->label(), 1, $translate('Resource templates')); ?>

<?php
echo $this->partial(
    'omeka/admin/resource-template/form.phtml',
    [
        'form' => $form,
        'propertyFieldset' => $propertyFieldset,
        'resourceTemplate' => $resourceTemplate,
        'submitLabel' => $translate('Save'),
        'action' => 'edit',
    ]
);
?>

<?php $this->trigger('view.edit.after'); ?>
